# Generated by Django 5.1.6 on 2025-03-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatos',
            name='talla',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zapatos',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='zapatos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='zapatos',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='zapatos',
            table='zapatos',
        ),
    ]
