# Generated by Django 5.1.6 on 2025-03-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos_app', '0002_zapatos_talla_alter_zapatos_img_alter_zapatos_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatos',
            name='stock',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
