# Generated by Django 5.1.6 on 2025-03-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos_app', '0003_alter_zapatos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatos',
            name='img',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='zapatos',
            name='precio',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterModelTable(
            name='zapatos',
            table=None,
        ),
    ]
